### ISSUE TITLE
Add screencast of plugin in action

### ISSUE THREAD

**Issue by RonanMacF** [ChanderG/tmux-notify#18]
The idea is good however it doesn't seem to work for me :( Running on CentOS system with 3.1c. When I do `prefix + alt + m` I get message saying pane is already being monitored, I run `sleep 15` but when the command finished focus is not regained and no notifications. I would like to see how it should work.

**Comment by rickstaa** [comment]
Hey, @RonanMacF Thanks a lot for taking an interest in our plugin. I think you came across a use-case in which the following check fails:

https://github.com/ChanderG/tmux-notify/blob/52b086bce19d659632e393e1aa478c0d04413289/scripts/notify.sh#L43

Are you familiar enough with a bash to debug the issue yourself and supply a pull request? Otherwise, I will need to spin-up a CentOS VM to check this issue. In that case, I will need the exact version of CentOs, Shell, Tmux and Tmux-notify plugin versions.

**Comment by rickstaa** [comment]
@RonanMacF Just curious, did you manage to solve the problem on your setup? If not, I am happy to help if you provide me with your system details.

**Comment by rickstaa** [comment]
@rickstaa I will close this for now due to the lack of information. Feel free to comment on this issue if you want it reopened. It might be that pull request #21 fixes your problem.
