### ISSUE TITLE
Support/docs for setting up host notifications from within a docker container 

### ISSUE THREAD

**Issue by mihaigalos** [ChanderG/tmux-notify#30]
**Is your feature request related to a problem? Please describe.**
Tried running in a docker container, all deps installed (bash, notify-send).
Please offer support/docs for setting up host notifications from within a docker container.

**Describe the solution you'd like**
Be notified when a monitored process finishes in the docker container.

**Describe alternatives you've considered**
None, any suggestions are useful.

**Additional context**
None.

**Comment by rickstaa** [comment]
@mihaigalos I haven't found a way to use this within a docker container. You are welcome to create a pull request if you found a way.

**Comment by rickstaa** [comment]
Maybe this helps https://github.com/mikaelbr/node-notifier/issues/200.

**Comment by rickstaa** [comment]
> Maybe this helps [mikaelbr/node-notifier#200](https://github.com/mikaelbr/node-notifier/issues/200).

Related to #36.

**Comment by rickstaa** [comment]
@mihaigalos I tested it out, and I was able to get tmux-notify to work inside a docker container. You can find the documentation and an example on https://github.com/rickstaa/tmux-notify#use-inside-a-docker-container. 

I am happy to merge it back into this upstream, but for now, it looks like this repository is no longer maintained (see https://github.com/ChanderG/tmux-notify/issues/28#issuecomment-1584456420). As a result, after 3 years, I decided to maintain the repository on a detached-fork since this will give me more control 😅.

**Comment by rickstaa** [comment]
> @mihaigalos I tested it out, and I was able to get tmux-notify to work inside a docker container. You can find the documentation and an example on https://github.com/rickstaa/tmux-notify#use-inside-a-docker-container.
> 
> I am happy to merge it back into this upstream, but for now, it looks like this repository is no longer maintained (see [#28 (comment)](https://github.com/ChanderG/tmux-notify/issues/28#issuecomment-1584456420)). As a result, after 3 years, I decided to maintain the repository on a detached-fork since this will give me more control sweat_smile.

Please let me know if the solution works for you 🙏🏻!
